-- Test Credit Card Application Flow
-- This script tests the complete application submission process

-- Test 1: Create a test customer
SELECT 'Test 1: Creating test customer...' AS TEST_STEP FROM DUAL;

-- Check if test customer exists
SELECT COUNT(*) AS EXISTING_CUSTOMERS FROM CC_CUSTOMER WHERE SSN = '123-45-6789';

-- Test 2: Insert test application data
SELECT 'Test 2: Testing application insertion...' AS TEST_STEP FROM DUAL;

-- Get next IDs
SELECT SEQ_CUSTOMER_ID.NEXTVAL AS NEXT_CUSTOMER_ID FROM DUAL;
SELECT SEQ_APPLICATION_ID.NEXTVAL AS NEXT_APPLICATION_ID FROM DUAL;

-- Test 3: Verify all constraints and data types
SELECT 'Test 3: Verifying table structures...' AS TEST_STEP FROM DUAL;

-- Check HOME_OWNERSHIP constraint
SELECT CONSTRAINT_NAME, CHECK_CLAUSE 
FROM INFORMATION_SCHEMA.CONSTRAINTS 
WHERE TABLE_NAME = 'CC_APPLICANT_FINANCIAL' 
AND CONSTRAINT_TYPE = 'CHECK'
AND CONSTRAINT_NAME = 'CHK_HOME_OWNERSHIP';

-- Check EMPLOYMENT_TYPE constraint  
SELECT CONSTRAINT_NAME, CHECK_CLAUSE 
FROM INFORMATION_SCHEMA.CONSTRAINTS 
WHERE TABLE_NAME = 'CC_APPLICANT_EMPLOYMENT' 
AND CONSTRAINT_TYPE = 'CHECK'
AND CONSTRAINT_NAME = 'CHK_EMP_TYPE';

-- Test 4: Verify column sizes
SELECT 'Test 4: Verifying column sizes...' AS TEST_STEP FROM DUAL;

SELECT TABLE_NAME, COLUMN_NAME, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('CC_APPLICANT_FINANCIAL', 'CC_APPLICANT_EMPLOYMENT')
AND COLUMN_NAME IN ('HOME_OWNERSHIP', 'EMPLOYMENT_TYPE')
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT 'All tests completed!' AS RESULT FROM DUAL;

-- Made with Bob
