package com.firstbank.creditcard.service;

import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.naming.InitialContext;

import com.firstbank.creditcard.ejb.session.CreditCardApplicationHome;
import com.firstbank.creditcard.ejb.session.CreditCardApplicationRemote;
import com.firstbank.creditcard.vo.ApplicationVO;
import com.firstbank.creditcard.vo.CustomerVO;

/**
 * CreditCardServiceImpl - SOAP Web Service Implementation.
 * Delegates all business operations to the EJB tier.
 * Registered with Apache AXIS as a web service endpoint.
 *
 * Apache AXIS 1.x deployment descriptor (server-config.wsdd) registers
 * this class as the service implementation.
 *
 * Service WSDL generated by: java org.apache.axis.wsdl.Java2WSDL \
 *   -o wsdl/CreditCardService.wsdl \
 *   -l http://localhost:7001/creditcard/services/CreditCardService \
 *   -n urn:creditcard.firstbank.com \
 *   com.firstbank.creditcard.service.CreditCardServiceIF
 *
 * @author  FirstBank IT Department - Integration Team
 * @version 1.0  2001-06-15
 * @since   Apache AXIS 1.x / JAX-RPC 1.0
 */
public class CreditCardServiceImpl implements CreditCardServiceIF {

    private static final Logger logger =
        Logger.getLogger(CreditCardServiceImpl.class.getName());

    private static final String EJB_JNDI_NAME = "ejb/CreditCardApplicationBean";
    private static final String DATE_FORMAT    = "yyyy-MM-dd";

    // ----------------------------------------------------------
    // Service Methods
    // ----------------------------------------------------------

    /**
     * Submits a credit card application from a branch/partner system via SOAP.
     * Translates SOAP request beans to/from internal Value Objects and
     * delegates to the EJB session bean.
     *
     * @param request  SOAP request with all applicant data
     * @return         SOAP response with application ID and status
     * @throws RemoteException on service error
     */
    public CreditCardApplicationResponse submitApplication(CreditCardApplicationRequest request)
            throws RemoteException {
        logger.info("SOAP submitApplication() invoked for: " + request.getFirstName() + " " + request.getLastName());

        CreditCardApplicationResponse response = new CreditCardApplicationResponse();

        try {
            // Validate mandatory fields
            if (request.getSsn() == null || request.getSsn().trim().length() == 0) {
                response.setSuccess(false);
                response.setErrorCode("MISSING_SSN");
                response.setErrorMessage("SSN is required for application processing.");
                return response;
            }

            // Build CustomerVO
            CustomerVO customerVO = new CustomerVO();
            customerVO.setFirstName(request.getFirstName());
            customerVO.setMiddleName(request.getMiddleName());
            customerVO.setLastName(request.getLastName());
            customerVO.setSsn(request.getSsn());
            customerVO.setGender(request.getGender());
            customerVO.setEmailAddress(request.getEmailAddress());
            customerVO.setPhoneHome(request.getPhoneHome());
            customerVO.setPhoneWork(request.getPhoneWork());
            customerVO.setAddressLine1(request.getAddressLine1());
            customerVO.setAddressLine2(request.getAddressLine2());
            customerVO.setCity(request.getCity());
            customerVO.setStateCode(request.getStateCode());
            customerVO.setZipCode(request.getZipCode());
            customerVO.setCountryCode("US");

            // Parse date of birth
            try {
                SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT);
                sdf.setLenient(false);
                Date dob = sdf.parse(request.getDateOfBirth());
                customerVO.setDateOfBirth(dob);
            } catch (ParseException pe) {
                response.setSuccess(false);
                response.setErrorCode("INVALID_DOB");
                response.setErrorMessage("Date of birth must be in YYYY-MM-DD format.");
                return response;
            }

            // Build ApplicationVO
            ApplicationVO appVO = new ApplicationVO();
            appVO.setCardTypeId(request.getCardTypeId());
            appVO.setRequestedLimit(request.getRequestedLimit());
            appVO.setAnnualIncome(request.getAnnualIncome());
            appVO.setOtherIncome(request.getOtherIncome());
            appVO.setMonthlyRent(request.getMonthlyRent());
            appVO.setTotalDebt(request.getTotalDebt());
            appVO.setHomeOwnership(request.getHomeOwnership());
            appVO.setBankruptcyFlag(request.getBankruptcyFlag());
            appVO.setEmploymentType(request.getEmploymentType());
            appVO.setEmployerName(request.getEmployerName());
            appVO.setJobTitle(request.getJobTitle());
            appVO.setYearsEmployed(request.getYearsEmployed());
            appVO.setChannelCode(request.getChannelCode() != null ?
                                 request.getChannelCode() : "SOAP");

            // Invoke EJB
            String createdBy = "SOAP_" + (request.getAgentId() != null ?
                                request.getAgentId() : "EXTERNAL");
            CreditCardApplicationRemote ejb = getEJB();
            long applicationId = ejb.processApplication(customerVO, appVO, createdBy);

            // Build successful response
            response.setSuccess(true);
            response.setApplicationId(String.valueOf(applicationId));
            response.setStatusCode("PENDING");
            response.setStatusDescription("Application received and is pending review.");

            logger.info("SOAP submitApplication() succeeded. AppId: " + applicationId);

        } catch (Exception e) {
            logger.log(Level.SEVERE, "SOAP submitApplication() error", e);
            response.setSuccess(false);
            response.setErrorCode("SYSTEM_ERROR");
            response.setErrorMessage("System error processing application. Please retry. Detail: " + e.getMessage());
        }

        return response;
    }

    /**
     * Retrieves the current status of a submitted application via SOAP.
     *
     * @param applicationId  Application reference number as string
     * @return               Status response object
     * @throws RemoteException on service error
     */
    public ApplicationStatusResponse getApplicationStatus(String applicationId)
            throws RemoteException {
        logger.info("SOAP getApplicationStatus() for applicationId: " + applicationId);

        ApplicationStatusResponse response = new ApplicationStatusResponse();

        try {
            long appId = Long.parseLong(applicationId);
            CreditCardApplicationRemote ejb = getEJB();
            ApplicationVO appVO = ejb.getApplicationStatus(appId);

            response.setSuccess(true);
            response.setApplicationId(applicationId);
            response.setStatusCode(appVO.getStatusCode());
            response.setStatusDescription(appVO.getStatusDescription());
            response.setApprovedLimit(appVO.getApprovedLimit());
            response.setRejectionReason(appVO.getRejectionReasonDesc());

        } catch (NumberFormatException nfe) {
            response.setSuccess(false);
            response.setErrorCode("INVALID_APP_ID");
            response.setErrorMessage("Application ID must be a numeric value.");
        } catch (Exception e) {
            logger.log(Level.SEVERE, "SOAP getApplicationStatus() error", e);
            response.setSuccess(false);
            response.setErrorCode("SYSTEM_ERROR");
            response.setErrorMessage("Error retrieving application status: " + e.getMessage());
        }

        return response;
    }

    /**
     * Returns a list of available card types from the database.
     *
     * @return  Array of CardTypeInfo beans
     * @throws RemoteException on service error
     */
    public CardTypeInfo[] getCardTypes() throws RemoteException {
        logger.info("SOAP getCardTypes() invoked");

        try {
            CreditCardApplicationRemote ejb = getEJB();
            List cardTypeList = ejb.getAvailableCardTypes();

            CardTypeInfo[] cardTypes = new CardTypeInfo[cardTypeList.size()];
            for (int i = 0; i < cardTypeList.size(); i++) {
                String[] row = (String[]) cardTypeList.get(i);
                CardTypeInfo info = new CardTypeInfo();
                info.setCardTypeId(Integer.parseInt(row[0]));
                info.setCardTypeName(row[1]);
                info.setCardTypeCode(row[2]);
                info.setCreditLimitMin(Double.parseDouble(row[3]));
                info.setCreditLimitMax(Double.parseDouble(row[4]));
                info.setAnnualFee(Double.parseDouble(row[5]));
                info.setInterestRate(Double.parseDouble(row[6]));
                info.setMinIncomeRequired(Double.parseDouble(row[7]));
                cardTypes[i] = info;
            }
            return cardTypes;

        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error in SOAP getCardTypes()", e);
            throw new RemoteException("Error retrieving card types: " + e.getMessage(), e);
        }
    }

    // ----------------------------------------------------------
    // Private: EJB lookup helper
    // ----------------------------------------------------------

    private CreditCardApplicationRemote getEJB() throws Exception {
        InitialContext ctx = new InitialContext();
        CreditCardApplicationHome home =
            (CreditCardApplicationHome) javax.rmi.PortableRemoteObject.narrow(
                ctx.lookup(EJB_JNDI_NAME), CreditCardApplicationHome.class);
        return home.create();
    }
}
