-- ============================================================
-- FirstBank Credit Card Application System
-- Oracle 9i Database Schema
-- Created: 2001-06-15  Author: DBA Team - FirstBank IT Dept
-- ============================================================

-- Drop existing objects (run only if re-initializing)
-- DROP SEQUENCE SEQ_APPLICATION_ID;
-- DROP SEQUENCE SEQ_CUSTOMER_ID;
-- DROP SEQUENCE SEQ_CARD_ID;
-- DROP TABLE CC_APPLICATION_AUDIT;
-- DROP TABLE CC_CREDIT_CARD;
-- DROP TABLE CC_APPLICANT_EMPLOYMENT;
-- DROP TABLE CC_APPLICANT_FINANCIAL;
-- DROP TABLE CC_APPLICATION;
-- DROP TABLE CC_CUSTOMER;
-- DROP TABLE CC_CARD_TYPE;
-- DROP TABLE CC_STATUS_CODE;
-- DROP TABLE CC_REJECTION_REASON;

-- ============================================================
-- SEQUENCES
-- ============================================================

CREATE SEQUENCE SEQ_CUSTOMER_ID
    START WITH 100001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_APPLICATION_ID
    START WITH 200001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CARD_ID
    START WITH 300001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_AUDIT_ID
    START WITH 400001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================================
-- LOOKUP / REFERENCE TABLES
-- ============================================================

CREATE TABLE CC_STATUS_CODE (
    STATUS_CODE      VARCHAR2(10)     NOT NULL,
    STATUS_DESC      VARCHAR2(100)    NOT NULL,
    ACTIVE_FLAG      CHAR(1)          DEFAULT 'Y' NOT NULL,
    CREATED_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CC_STATUS_CODE PRIMARY KEY (STATUS_CODE),
    CONSTRAINT CHK_STATUS_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
);

CREATE TABLE CC_CARD_TYPE (
    CARD_TYPE_ID     NUMBER(5)        NOT NULL,
    CARD_TYPE_CODE   VARCHAR2(10)     NOT NULL,
    CARD_TYPE_NAME   VARCHAR2(100)    NOT NULL,
    CREDIT_LIMIT_MIN NUMBER(12,2)     NOT NULL,
    CREDIT_LIMIT_MAX NUMBER(12,2)     NOT NULL,
    ANNUAL_FEE       NUMBER(10,2)     DEFAULT 0 NOT NULL,
    INTEREST_RATE    NUMBER(5,2)      NOT NULL,
    MIN_INCOME_REQ   NUMBER(12,2)     NOT NULL,
    ACTIVE_FLAG      CHAR(1)          DEFAULT 'Y' NOT NULL,
    CREATED_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CC_CARD_TYPE PRIMARY KEY (CARD_TYPE_ID),
    CONSTRAINT UK_CARD_TYPE_CODE UNIQUE (CARD_TYPE_CODE),
    CONSTRAINT CHK_CARD_ACTIVE CHECK (ACTIVE_FLAG IN ('Y','N'))
);

CREATE TABLE CC_REJECTION_REASON (
    REASON_CODE      VARCHAR2(10)     NOT NULL,
    REASON_DESC      VARCHAR2(255)    NOT NULL,
    ACTIVE_FLAG      CHAR(1)          DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_CC_REJECTION_REASON PRIMARY KEY (REASON_CODE)
);

-- ============================================================
-- CUSTOMER TABLE
-- ============================================================

CREATE TABLE CC_CUSTOMER (
    CUSTOMER_ID      NUMBER(10)       NOT NULL,
    FIRST_NAME       VARCHAR2(50)     NOT NULL,
    MIDDLE_NAME      VARCHAR2(50),
    LAST_NAME        VARCHAR2(50)     NOT NULL,
    DATE_OF_BIRTH    DATE             NOT NULL,
    GENDER           CHAR(1)          NOT NULL,
    SSN              VARCHAR2(11)     NOT NULL,
    EMAIL_ADDRESS    VARCHAR2(100),
    PHONE_HOME       VARCHAR2(15),
    PHONE_WORK       VARCHAR2(15),
    PHONE_MOBILE     VARCHAR2(15),
    ADDRESS_LINE1    VARCHAR2(100)    NOT NULL,
    ADDRESS_LINE2    VARCHAR2(100),
    CITY             VARCHAR2(50)     NOT NULL,
    STATE_CODE       CHAR(2)          NOT NULL,
    ZIP_CODE         VARCHAR2(10)     NOT NULL,
    COUNTRY_CODE     CHAR(2)          DEFAULT 'US' NOT NULL,
    CUSTOMER_STATUS  VARCHAR2(10)     DEFAULT 'ACTIVE' NOT NULL,
    CREATED_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    CREATED_BY       VARCHAR2(30)     DEFAULT USER NOT NULL,
    UPDATED_DATE     DATE,
    UPDATED_BY       VARCHAR2(30),
    CONSTRAINT PK_CC_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CC_CUSTOMER_SSN UNIQUE (SSN),
    CONSTRAINT CHK_CUSTOMER_GENDER CHECK (GENDER IN ('M','F','O'))
);

CREATE INDEX IDX_CUST_SSN ON CC_CUSTOMER(SSN);
CREATE INDEX IDX_CUST_NAME ON CC_CUSTOMER(LAST_NAME, FIRST_NAME);
CREATE INDEX IDX_CUST_EMAIL ON CC_CUSTOMER(EMAIL_ADDRESS);

-- ============================================================
-- APPLICATION TABLE
-- ============================================================

CREATE TABLE CC_APPLICATION (
    APPLICATION_ID   NUMBER(10)       NOT NULL,
    CUSTOMER_ID      NUMBER(10)       NOT NULL,
    CARD_TYPE_ID     NUMBER(5)        NOT NULL,
    APPLICATION_DATE DATE             DEFAULT SYSDATE NOT NULL,
    STATUS_CODE      VARCHAR2(10)     DEFAULT 'PENDING' NOT NULL,
    REQUESTED_LIMIT  NUMBER(12,2),
    APPROVED_LIMIT   NUMBER(12,2),
    CREDIT_SCORE     NUMBER(5),
    REJECTION_REASON VARCHAR2(10),
    ANALYST_ID       VARCHAR2(30),
    REVIEW_DATE      DATE,
    REVIEW_NOTES     VARCHAR2(4000),
    IP_ADDRESS       VARCHAR2(20),
    CHANNEL_CODE     VARCHAR2(10)     DEFAULT 'WEB' NOT NULL,
    CREATED_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    CREATED_BY       VARCHAR2(30)     DEFAULT USER NOT NULL,
    UPDATED_DATE     DATE,
    UPDATED_BY       VARCHAR2(30),
    CONSTRAINT PK_CC_APPLICATION PRIMARY KEY (APPLICATION_ID),
    CONSTRAINT FK_APP_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CC_CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_APP_CARD_TYPE FOREIGN KEY (CARD_TYPE_ID)
        REFERENCES CC_CARD_TYPE(CARD_TYPE_ID),
    CONSTRAINT FK_APP_STATUS FOREIGN KEY (STATUS_CODE)
        REFERENCES CC_STATUS_CODE(STATUS_CODE),
    CONSTRAINT FK_APP_REJECTION FOREIGN KEY (REJECTION_REASON)
        REFERENCES CC_REJECTION_REASON(REASON_CODE)
);

CREATE INDEX IDX_APP_CUSTOMER ON CC_APPLICATION(CUSTOMER_ID);
CREATE INDEX IDX_APP_STATUS ON CC_APPLICATION(STATUS_CODE);
CREATE INDEX IDX_APP_DATE ON CC_APPLICATION(APPLICATION_DATE);

-- ============================================================
-- APPLICANT FINANCIAL INFORMATION
-- ============================================================

CREATE TABLE CC_APPLICANT_FINANCIAL (
    FINANCIAL_ID     NUMBER(10)       NOT NULL,
    APPLICATION_ID   NUMBER(10)       NOT NULL,
    ANNUAL_INCOME    NUMBER(14,2)     NOT NULL,
    OTHER_INCOME     NUMBER(14,2)     DEFAULT 0,
    MONTHLY_RENT     NUMBER(10,2)     DEFAULT 0,
    MORTGAGE_BALANCE NUMBER(14,2)     DEFAULT 0,
    TOTAL_DEBT       NUMBER(14,2)     DEFAULT 0,
    CHECKING_BALANCE NUMBER(14,2)     DEFAULT 0,
    SAVINGS_BALANCE  NUMBER(14,2)     DEFAULT 0,
    HOME_OWNERSHIP   VARCHAR2(10),
    BANKRUPTCY_FLAG  CHAR(1)          DEFAULT 'N',
    BANKRUPTCY_DATE  DATE,
    CREATED_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CC_APPLICANT_FINANCIAL PRIMARY KEY (FINANCIAL_ID),
    CONSTRAINT FK_FIN_APPLICATION FOREIGN KEY (APPLICATION_ID)
        REFERENCES CC_APPLICATION(APPLICATION_ID),
    CONSTRAINT CHK_BANKRUPTCY CHECK (BANKRUPTCY_FLAG IN ('Y','N')),
    CONSTRAINT CHK_HOME_OWNERSHIP CHECK (HOME_OWNERSHIP IN ('OWN','RENT','LIVE_WITH_PARENTS','OTHER'))
);

-- ============================================================
-- APPLICANT EMPLOYMENT INFORMATION
-- ============================================================

CREATE TABLE CC_APPLICANT_EMPLOYMENT (
    EMPLOYMENT_ID    NUMBER(10)       NOT NULL,
    APPLICATION_ID   NUMBER(10)       NOT NULL,
    EMPLOYMENT_TYPE  VARCHAR2(20)     NOT NULL,
    EMPLOYER_NAME    VARCHAR2(100),
    EMPLOYER_PHONE   VARCHAR2(15),
    JOB_TITLE        VARCHAR2(100),
    YEARS_EMPLOYED   NUMBER(3),
    MONTHS_EMPLOYED  NUMBER(2),
    EMPLOYER_ADDRESS VARCHAR2(200),
    CREATED_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CC_APPLICANT_EMPLOYMENT PRIMARY KEY (EMPLOYMENT_ID),
    CONSTRAINT FK_EMP_APPLICATION FOREIGN KEY (APPLICATION_ID)
        REFERENCES CC_APPLICATION(APPLICATION_ID),
    CONSTRAINT CHK_EMP_TYPE CHECK (EMPLOYMENT_TYPE IN (
        'FULL_TIME','PART_TIME','SELF_EMPLOYED','RETIRED','STUDENT','UNEMPLOYED'))
);

-- ============================================================
-- APPROVED CREDIT CARD TABLE
-- ============================================================

CREATE TABLE CC_CREDIT_CARD (
    CARD_ID          NUMBER(10)       NOT NULL,
    APPLICATION_ID   NUMBER(10)       NOT NULL,
    CUSTOMER_ID      NUMBER(10)       NOT NULL,
    CARD_TYPE_ID     NUMBER(5)        NOT NULL,
    CARD_NUMBER      VARCHAR2(20)     NOT NULL,
    CARD_HOLDER_NAME VARCHAR2(100)    NOT NULL,
    EXPIRY_MONTH     NUMBER(2)        NOT NULL,
    EXPIRY_YEAR      NUMBER(4)        NOT NULL,
    CVV_HASH         VARCHAR2(64)     NOT NULL,
    CREDIT_LIMIT     NUMBER(12,2)     NOT NULL,
    AVAILABLE_CREDIT NUMBER(12,2)     NOT NULL,
    CARD_STATUS      VARCHAR2(10)     DEFAULT 'INACTIVE' NOT NULL,
    ISSUE_DATE       DATE             DEFAULT SYSDATE NOT NULL,
    ACTIVATION_DATE  DATE,
    LAST_USED_DATE   DATE,
    CREATED_DATE     DATE             DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CC_CREDIT_CARD PRIMARY KEY (CARD_ID),
    CONSTRAINT FK_CARD_APPLICATION FOREIGN KEY (APPLICATION_ID)
        REFERENCES CC_APPLICATION(APPLICATION_ID),
    CONSTRAINT FK_CARD_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CC_CUSTOMER(CUSTOMER_ID),
    CONSTRAINT UK_CC_CARD_NUMBER UNIQUE (CARD_NUMBER)
);

-- ============================================================
-- AUDIT LOG TABLE
-- ============================================================

CREATE TABLE CC_APPLICATION_AUDIT (
    AUDIT_ID         NUMBER(10)       NOT NULL,
    APPLICATION_ID   NUMBER(10)       NOT NULL,
    ACTION_CODE      VARCHAR2(20)     NOT NULL,
    OLD_STATUS       VARCHAR2(10),
    NEW_STATUS       VARCHAR2(10),
    ACTION_BY        VARCHAR2(30)     NOT NULL,
    ACTION_DATE      DATE             DEFAULT SYSDATE NOT NULL,
    ACTION_NOTES     VARCHAR2(1000),
    IP_ADDRESS       VARCHAR2(20),
    CONSTRAINT PK_CC_AUDIT PRIMARY KEY (AUDIT_ID)
);

-- ============================================================
-- SEED DATA - REFERENCE TABLES
-- ============================================================

INSERT INTO CC_STATUS_CODE VALUES ('PENDING',  'Application Pending Review',        'Y', SYSDATE);
INSERT INTO CC_STATUS_CODE VALUES ('REVIEW',   'Under Manual Review',               'Y', SYSDATE);
INSERT INTO CC_STATUS_CODE VALUES ('APPROVED', 'Application Approved',              'Y', SYSDATE);
INSERT INTO CC_STATUS_CODE VALUES ('REJECTED', 'Application Rejected',              'Y', SYSDATE);
INSERT INTO CC_STATUS_CODE VALUES ('WAITLIST', 'On Waitlist',                       'Y', SYSDATE);
INSERT INTO CC_STATUS_CODE VALUES ('CANCELLED','Application Cancelled by Applicant','Y', SYSDATE);
INSERT INTO CC_STATUS_CODE VALUES ('ACTIVE',   'Customer Active',                   'Y', SYSDATE);

INSERT INTO CC_REJECTION_REASON VALUES ('LOW_SCORE',  'Credit score does not meet minimum requirement', 'Y');
INSERT INTO CC_REJECTION_REASON VALUES ('LOW_INCOME', 'Annual income below minimum threshold',           'Y');
INSERT INTO CC_REJECTION_REASON VALUES ('BANKRUPTCY', 'Recent bankruptcy on record',                     'Y');
INSERT INTO CC_REJECTION_REASON VALUES ('HIGH_DEBT',  'Debt-to-income ratio too high',                   'Y');
INSERT INTO CC_REJECTION_REASON VALUES ('INCOMPLETE', 'Application information is incomplete',           'Y');
INSERT INTO CC_REJECTION_REASON VALUES ('DUPLICATE',  'Duplicate application exists',                    'Y');
INSERT INTO CC_REJECTION_REASON VALUES ('FRAUD',      'Suspected fraudulent application',                'Y');
INSERT INTO CC_REJECTION_REASON VALUES ('AGE',        'Applicant does not meet minimum age requirement', 'Y');

INSERT INTO CC_CARD_TYPE VALUES (1, 'CLASSIC',   'FirstBank Classic Visa',        500,    5000,  35,  19.99, 18000,  'Y', SYSDATE);
INSERT INTO CC_CARD_TYPE VALUES (2, 'GOLD',      'FirstBank Gold Visa',           2500,  15000,  75,  17.99, 35000,  'Y', SYSDATE);
INSERT INTO CC_CARD_TYPE VALUES (3, 'PLATINUM',  'FirstBank Platinum MasterCard', 5000,  30000, 125,  15.99, 60000,  'Y', SYSDATE);
INSERT INTO CC_CARD_TYPE VALUES (4, 'TITANIUM',  'FirstBank Titanium Card',      10000,  75000, 250,  13.99, 100000, 'Y', SYSDATE);
INSERT INTO CC_CARD_TYPE VALUES (5, 'STUDENT',   'FirstBank Student Visa',         300,   2000,   0,  21.99, 0,      'Y', SYSDATE);
INSERT INTO CC_CARD_TYPE VALUES (6, 'BUSINESS',  'FirstBank Business Card',       5000, 100000, 199,  14.99, 80000,  'Y', SYSDATE);

COMMIT;

-- ============================================================
-- SYNONYMS (for application user)
-- ============================================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON CC_CUSTOMER TO ccapp_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON CC_APPLICATION TO ccapp_user;
-- GRANT SELECT, INSERT, UPDATE ON CC_APPLICANT_FINANCIAL TO ccapp_user;
-- GRANT SELECT, INSERT, UPDATE ON CC_APPLICANT_EMPLOYMENT TO ccapp_user;
-- GRANT SELECT, INSERT, UPDATE ON CC_CREDIT_CARD TO ccapp_user;
-- GRANT SELECT ON CC_CARD_TYPE TO ccapp_user;
-- GRANT SELECT ON CC_STATUS_CODE TO ccapp_user;
-- GRANT SELECT ON CC_REJECTION_REASON TO ccapp_user;
-- GRANT INSERT ON CC_APPLICATION_AUDIT TO ccapp_user;
-- GRANT SELECT, USAGE ON SEQ_CUSTOMER_ID TO ccapp_user;
-- GRANT SELECT, USAGE ON SEQ_APPLICATION_ID TO ccapp_user;
-- GRANT SELECT, USAGE ON SEQ_CARD_ID TO ccapp_user;
-- GRANT SELECT, USAGE ON SEQ_AUDIT_ID TO ccapp_user;
